name: Spring Boot & Gradle CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    uses: kjiyun/CI-CD-pipeline-standard/.github/workflows/java-gradle-ci.yml@master
    # 참고: https://github.com/kjiyun/CI-CD-pipeline-standard
    with:
      java-version: "17"
      distribution: "temurin"
      build-command: "false"
      test-command: "false"
      upload-artifacts: true
      write-application-yml: true
    secrets:
      APPLICATION: ${{ secrets.APPLICATION }}

